//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newLife
{
    using System;
    using System.Collections.Generic;
    
    public partial class Building
    {
        public string Building_Name { get; set; }
        public int Building_totalStory { get; set; }
        public string B_WardName { get; set; }
        public string B_WardFloor { get; set; }
        public string B_RoomNumber { get; set; }
        public int B_RoomCapacity { get; set; }
    }
}
