//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newLife
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewPatient
    {
        public int Patient_Id { get; set; }
        public string Patient_FirstName { get; set; }
        public string Patient_MiddleName { get; set; }
        public string Patient_LastName { get; set; }
        public string Patient_Region { get; set; }
        public string Patient_Zone { get; set; }
        public string Patient_Town { get; set; }
        public string Patient_Kebele { get; set; }
        public string Patient_Sex { get; set; }
        public short Patient_Age { get; set; }
        public System.DateTime Patient_CheckIn { get; set; }
        public string Patient_Marriage_Status { get; set; }
        public string Patient_Ethinicity { get; set; }
        public string Patient_occupation { get; set; }
        public string Patient_Religion { get; set; }
        public string Patient_Referred_From { get; set; }
        public Nullable<int> Patient_Bed { get; set; }
        public string Patient_Status { get; set; }
        public Nullable<System.DateTime> Patient_Checkout { get; set; }
        public string Patient_Room { get; set; }
        public string Patient_WardName { get; set; }
        public string Patient_WardFloor { get; set; }
    }
}
