//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newLife
{
    using System;
    using System.Collections.Generic;
    
    public partial class Register_Users
    {
        public long user_id { get; set; }
        public string First_Name { get; set; }
        public string Second_Name { get; set; }
        public string Phone_No { get; set; }
        public string Password_user { get; set; }
    }
}
