//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newLife
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBnewLifeEntities : DbContext
    {
        public DBnewLifeEntities()
            : base("name=DBnewLifeEntities")
        {
            Database.SetInitializer<DBnewLifeEntities>(new CreateDatabaseIfNotExists<DBnewLifeEntities>());
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Register_User> Register_User { get; set; }
    }
}
